@extends('layouts.management')
@section('title', 'Payments')
@section('page-label', 'Payments')
@section('content')
<div class="page-heading"><div><p class="section-kicker">Financial records</p><h1>Payments</h1><p>Review room and event payment records, statuses, and receipts.</p></div><a href="{{ route('payments.create') }}" class="btn btn-hotel"><i class="bi bi-plus-lg me-1"></i> Add Payment</a></div>
<div class="table-card"><div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th class="ps-4">Reference</th><th>User</th><th>Related booking</th><th>Amount</th><th>Method</th><th>Date</th><th>Status</th><th class="text-end pe-4">Actions</th></tr></thead><tbody>
@forelse($payments as $payment)<tr><td class="ps-4"><strong>{{ $payment->reference_number }}</strong><small class="d-block text-muted">#{{ $payment->id }}</small></td><td>@if($payment->user)<strong>{{ $payment->user->name }}</strong><small class="d-block text-muted">{{ $payment->user->email }}</small>@else User #{{ $payment->user_id }} @endif</td><td>@if($payment->event_booking_id)<span class="badge text-bg-light border">Event #{{ $payment->event_booking_id }}</span>@if($payment->eventBooking)<small class="d-block text-muted">{{ $payment->eventBooking->venue?->name ?? 'Venue unavailable' }} · {{ $payment->eventBooking->starts_at?->format('M j, Y') ?? 'Date unavailable' }}</small>@else<small class="d-block text-muted">Record unavailable</small>@endif @elseif($payment->booking_id)<span class="badge text-bg-light border">Room booking #{{ $payment->booking_id }}</span>@else<span class="text-muted">—</span>@endif</td><td class="fw-semibold">${{ number_format($payment->amount,2) }}</td><td>{{ $payment->payment_method }}</td><td>{{ $payment->payment_date?->format('M j, Y') }}</td><td><x-status-badge :status="$payment->status" /></td><td class="text-end pe-4 text-nowrap"><a href="{{ route('payments.show',$payment) }}" class="btn btn-sm btn-outline-primary"><i class="bi bi-eye"></i></a> <a href="{{ route('payments.edit',$payment) }}" class="btn btn-sm btn-outline-secondary"><i class="bi bi-pencil"></i></a> <form action="{{ route('payments.destroy',$payment) }}" method="POST" class="d-inline">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" data-confirm="Delete payment {{ $payment->reference_number }}?" type="submit"><i class="bi bi-trash"></i></button></form></td></tr>
@empty<tr><td colspan="8"><x-empty-state icon="bi-receipt" title="No payments found" message="Add the first payment record to begin tracking revenue."><a href="{{ route('payments.create') }}" class="btn btn-hotel">Add Payment</a></x-empty-state></td></tr>@endforelse
</tbody></table></div></div>
@if($payments->hasPages())<div class="mt-4">{{ $payments->links('pagination::bootstrap-5') }}</div>@endif
@endsection
