@extends(request()->routeIs('management.facilities.*') ? 'layouts.management' : 'layouts.app')
@section('title', 'Facilities & Amenities')
@section('page-label', 'Facilities')
@section('content')
@php($managing = request()->routeIs('management.facilities.*'))
@unless($managing)<section class="page-hero"><div class="container"><p class="section-kicker">More than a stay</p><h1>Facilities designed around you</h1><p>Discover the amenities and services that make every hotel visit more comfortable.</p></div></section>@endunless
<section class="{{ $managing ? '' : 'content-section' }}"><div class="{{ $managing ? '' : 'container' }}">
    <div class="page-heading"><div>@if($managing)<p class="section-kicker">Guest experience</p>@endif<h1>{{ $managing ? 'Manage Facilities' : 'Facilities & Amenities' }}</h1><p>{{ $managing ? 'Maintain the amenities available across hotel rooms.' : 'Thoughtful details for a more enjoyable stay.' }}</p></div>@if($managing)<div class="d-flex gap-2"><a href="{{ route('management.rooms.index') }}" class="btn btn-outline-secondary">Rooms</a><a href="{{ route('management.facilities.create') }}" class="btn btn-hotel"><i class="bi bi-plus-lg me-1"></i> Add Facility</a></div>@endif</div>
    @if($managing)
        <div class="table-card"><div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th class="ps-4">Facility</th><th>Description</th><th>Status</th><th class="text-end pe-4">Actions</th></tr></thead><tbody>@forelse($facilities as $facility)<tr><td class="ps-4"><strong>{{ $facility->name }}</strong></td><td class="text-muted">{{ Illuminate\Support\Str::limit($facility->description ?: 'No description provided.', 110) }}</td><td><x-status-badge :status="match((string) $facility->status) { '1', 'open' => 'available', 'maintenance' => 'maintenance', default => 'inactive' }" /></td><td class="text-end pe-4 text-nowrap"><a href="{{ route('management.facilities.show', $facility) }}" class="btn btn-sm btn-outline-primary"><i class="bi bi-eye"></i></a> <a href="{{ route('management.facilities.edit', $facility) }}" class="btn btn-sm btn-outline-secondary"><i class="bi bi-pencil"></i></a> <form action="{{ route('management.facilities.destroy', $facility) }}" method="POST" class="d-inline">@csrf @method('DELETE')<button type="submit" class="btn btn-sm btn-outline-danger" data-confirm="Delete {{ $facility->name }}?"><i class="bi bi-trash"></i></button></form></td></tr>@empty<tr><td colspan="4"><x-empty-state icon="bi-stars" title="No facilities found" message="Add an amenity to start building the hotel facility list." /></td></tr>@endforelse</tbody></table></div></div>
    @else
        <div class="row g-4">@forelse($facilities as $facility)<div class="col-md-6 col-lg-4"><article class="hotel-card service-card text-start"><i class="bi bi-stars"></i><div class="d-flex justify-content-between gap-3"><h2 class="h4">{{ $facility->name }}</h2><x-status-badge :status="match((string) $facility->status) { '1', 'open' => 'available', 'maintenance' => 'maintenance', default => 'unavailable' }" /></div><p>{{ $facility->description ?: 'Available to support a comfortable hotel experience.' }}</p><a href="{{ route('facilities.show', $facility) }}" class="btn btn-sm btn-outline-primary mt-2">Learn more</a></article></div>@empty<div class="col-12"><x-empty-state icon="bi-stars" title="Facilities coming soon" message="Our facility catalogue is being prepared." /></div>@endforelse</div>
    @endif
    @if($facilities->hasPages())<div class="mt-4">{{ $facilities->links('pagination::bootstrap-5') }}</div>@endif
</div></section>
@endsection
